// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvMR-23dQLAkgBv59hWoIY04r7wFk2JFs',
    appId: '1:212386922156:web:669d114855e6106f012909',
    messagingSenderId: '212386922156',
    projectId: 'espin-5f29a',
    authDomain: 'espin-5f29a.firebaseapp.com',
    storageBucket: 'espin-5f29a.appspot.com',
    measurementId: 'G-K9Q27B42LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ9rNVYgKw2hnkjGHqpoXq9Zt6eM0o1CM',
    appId: '1:212386922156:android:faeca42e18c998d5012909',
    messagingSenderId: '212386922156',
    projectId: 'espin-5f29a',
    storageBucket: 'espin-5f29a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBPxOvLtSn9vJR_iMppmcuXEpOEE8amrM',
    appId: '1:212386922156:ios:e18ce83e6283a77b012909',
    messagingSenderId: '212386922156',
    projectId: 'espin-5f29a',
    storageBucket: 'espin-5f29a.appspot.com',
    iosBundleId: 'com.example.firstappesin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBPxOvLtSn9vJR_iMppmcuXEpOEE8amrM',
    appId: '1:212386922156:ios:e18ce83e6283a77b012909',
    messagingSenderId: '212386922156',
    projectId: 'espin-5f29a',
    storageBucket: 'espin-5f29a.appspot.com',
    iosBundleId: 'com.example.firstappesin',
  );
}
